In [2]:
from pathlib import Path
import sys

import math
import numpy as np
sys.path.append(str(Path().cwd().parent))
import networkx as nx

In [ ]:
from matrix import srg_quotient_matrix, srg_quotient_matrix__one_self_loop

params = (3, 0, 1)
A1 = srg_quotient_matrix__one_self_loop(*params)
A = srg_quotient_matrix(*params)
# A[0, 0] = 1
# A[1, 1] = 1
print(np.linalg.eigvals(A1))
print(np.linalg.eigvals(A))




[-0.91222918  1.71353793  3.19869124]
[-1.41421356  1.41421356  3.        ]


In [15]:
G = nx.petersen_graph()

# Get the adjacency matrix as a NumPy array
# nodelist=range(10) ensures the order corresponds to standard labeling
A = nx.to_numpy_array(G, nodelist=range(10), dtype=int)
A[0, 0] = 1
A[1, 1] = 1
A[2, 2] = 1
A[3, 3] = 1
A[4, 4] = 1
A[5, 5] = 1
A[6, 6] = 1
A[7, 7] = 1
A[8, 8] = 1
# A[9, 9] = 1

tolerance = 1e-10

eigens = np.linalg.eigvalsh(A)

# rounded_eigenvalues = np.round(eigens / tolerance) * tolerance
# unique_eigenvalues = np.unique(rounded_eigenvalues)

# unique_eigenvalues
eigens


array([-1.47735235, -1.        , -1.        , -1.        ,  1.55192943,
        2.        ,  2.        ,  2.        ,  2.        ,  3.92542292])

In [ ]:
import numpy as np
from matrix import full_bipartite_graph


n, m = 2, 4
A = full_bipartite_graph(n, m)
for i in range(m):
    A[i, i] = 1

tolerance = 1e-10

eigens = np.linalg.eigvalsh(A)

rounded_eigenvalues = np.round(eigens / tolerance) * tolerance
unique_eigenvalues = np.unique(rounded_eigenvalues)

unique_eigenvalues


array([-2.14133612,  0.        ,  0.51513805,  1.        ,  3.62619807])

In [4]:
math.sqrt(n * m) + 1/2

3.3284271247461903